### ISSUE TITLE
code splitting works incorrect

### ISSUE THREAD

**Issue by berdof** [ctrlplusb/react-universally#100]
Hi, found very strange issue. After you run `npm run build` a lot of noise is present in output bundle. For instance if you search for __REACT_HOT_LOADER__ in build/client/main-*.js you will find something like this http://take.ms/lP1T3 . Removing hot loader condition from `src/shared/routes/index.js` caused strange splitting behaviour. Now all the chunks have __REACT_HOT_LOADER__ injections http://take.ms/qB0oB . Also some routes in my app have almost empty chunks but their contents presents in main.js. 

Do you have any ideas how to solve this?

**Comment by ctrlplusb** [comment]
I'll have to do some experimentation on my side to confirm what you are experiencing.  Do you have an example available?

**Comment by ctrlplusb** [comment]
@berdof Were you trying to debug code splitting whilst in development mode or production mode?

Currently code splitting should only work whilst using production mode code (i.e. `npm run build` && `npm run start`).

This is because of the current workaround for hot module reloading within the routes file which makes us specifically require each component explicitly

**Comment by ctrlplusb** [comment]
FYI I have a fix for issue #101 which will make the development hack go away...

**Comment by ctrlplusb** [comment]
New release should alleviate this. :)

**Comment by ctrlplusb** [comment]
@berdof I did locate another issue with webpack.  It's tree shaking feature doesn't work if importing boolean constants from another module.  I have had to inline the statements.

e.g. if (process.env.NODE_ENV === 'development')

This may have been causing some issues previously with code splitting.

The latest release addresses this.
