### ISSUE TITLE
Can't install sass

### ISSUE THREAD

**Issue by expdevelop** [ctrlplusb/react-universally#102]
I tried this in configFactory.js:
`{
          test: /\.sass$/,
          loader: ExtractTextPlugin.extract('style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap')
},`

And got this:
`ERROR in ./src/shared/components/App/App.sass
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example`

What's wrong?

**Comment by ctrlplusb** [comment]
Please be aware that because I am using webpack v2 for this project I am using the v2 beta release of `extract-text-webpack-plugin`.  Their API has changed slightly.  

You can read their docs here: https://github.com/webpack/extract-text-webpack-plugin

I think it should work if you adjust your configuration as per their recommendations.
