### ISSUE TITLE
[Question] Universal folder under src/shared

### ISSUE THREAD

**Issue by samkuhn** [ctrlplusb/react-universally#120]
Loving this boilerplate so far - really great.

Just a quick question: what's the purpose of the "universal" folder in src/shared? I'm guessing it's so we can create our app next to it in the shared folder - and keep "universal" around as a reference - possibly making it easier to merge in build improvements from upstream over time?

**Comment by ctrlplusb** [comment]
Thanks @samkuhn, I am glad you are finding it helpful! :)

In regards to the `universal` folder, my idea here was to simply provide a sub-folder structure within `shared` that would allow you to represent different types of "shared" files.  In my other projects I have added a `node` folder which basically contains JS that is shared between the `server` and the `universalMiddleware` bundles, but it is not appropriate for the `client` bundle (for example usage of `import fs from 'fs';`).

I should probably add an example within this project so that it's clearer though.

**Comment by ctrlplusb** [comment]
Hi @samkuhn I hope the above helps to clear this up.  Please let me know if there is anything else I can or should do to make this clearer for everyone.

I am closing this for now.  Thanks.

**Comment by samkuhn** [comment]
Yes, that makes sense. Thanks!
