### ISSUE TITLE
Including "/" in sw.js

### ISSUE THREAD

**Issue by bkniffler** [ctrlplusb/react-universally#188]
Why is "/" included in sw.js? In my case, it is impossible to serve fresh versions, as the "/" will always be served from cache and it will reference the cached assets.

**Comment by AndreasZeiser** [comment]
I agree on this. 

The cached response of "/" delivered by the service worker may contain references to previously cached assets which might have been replaced after a new deployment resulting in 404 responses.

**Comment by ctrlplusb** [comment]
Hi @bkniffler 

Thanks for the report!  This is definitely an oversight.  My thoughts was to support offline serving of the root route, but I should of course reconsider the caching issue.

Anyone with experience on this?

**Comment by ctrlplusb** [comment]
This is confirmed.  Trying out a few things.

**Comment by ctrlplusb** [comment]
Argh, the situation is actually really really bad.  I've had a play with the `offline-plugin` too which presents an alternative set of problems around pathing.

After much reading and going through github issues I can see now that creating a proper offline application is far more involved than I anticipated.  You have to control your cache invalidation strategies as well as ensure that you allow a method to activate any updated service worker content.

I could start bashing something out but I feel like it will introduce a significant amount of configuration complexity.  I definitely don't want things to get complicated, and certainly don't want it to be flaky. At this stage I think it may be best to simplify the hell out of the service worker configuration so that it only precaches/caches the webpack asset output, keeping all the public assets and paths such as '/' as requiring a network request.  We can introduce a fallback `offline.html` page too perhaps.

We can create a new issue in which we properly discuss and test a decent base offline application configuration.

Learning loads here though. :)

**Comment by ctrlplusb** [comment]
@bkniffler 

Haha, some good news!  It seems that whilst I was sleeping a new version of `offline-plugin` (v4) was published, and it contains a configuration option that allows me to solve the pathing issues I was alluding to before!

Making awesome progress on this.

**Comment by ctrlplusb** [comment]
@strues - ping

**Comment by ctrlplusb** [comment]
Ok, so I have this working much more nicely.

I have moved to `offline-plugin`.

The webpack generated assets are cached via the service worker, as well as all the public assets.

I have also included a script that will reload the application should any of the generated or public assets change.  The new service worker is accepted and the browser reloads.  This only occurs on file changes. I tested it against a simple change to one of the static assets in the public folder and it works as expected.

I am no longer caching dynamic urls such as '/'.  Instead I have introduced an "offline.html" page which will be served if a user no longer has any network connectivity.

Thoughts? @bkniffler @strues 

I want to push this ASAP, as things are broken with the current configuration.

**Comment by bkniffler** [comment]
Gonna pull the changes into the olymp repo as soon as you've pushed and then I can test, but I'm very positive on this solution! So lets do this 👍 

And serving an offline.html is totally cool and will definitely improve the user experience.

**Comment by ctrlplusb** [comment]
@bkniffler it's on the `next` branch. :)

**Comment by bkniffler** [comment]
Has this been merged already? Or is it still in the next branch only?
