### ISSUE TITLE
Seperate application configuration and environment settings.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#206]
Currently we are mixing application configuration with environment settings.  We need to separate these.

I have been playing with some ideas, and have ended up creating a `.config` folder, like so:

```
.config
   |- project.js
   |- client.js
   |- server.js
   |- development.js
```

Then the environment variables need only be concerned about the actual stuff that is likely to change between environments.  For example the new .env file looks like:

<img width="659" alt="screenshot 2016-11-30 13 26 30" src="https://cloud.githubusercontent.com/assets/12164768/20754074/21e1c8c0-b701-11e6-9683-bf1fd39b8969.png">

Much cleaner.

And as per @bkniffler's suggestion we can even make the .env file completely optional, having our config files have reasonable defaults.  Then it's up to you to provide environment overrides for the typical stuff that would need to be overridden.

**Comment by ctrlplusb** [comment]
Other cool things coming out of this:

 - .env file is optional
 - no longer need an .env_whitelist
 - simplified webpack config - don't need to pass env vars through the DefinePlugin.
 - overall simpler and easier to understand.

**Comment by ctrlplusb** [comment]
I've merged all the configs into a single `project.js` configuration file.  I've also introduce a check that will ensure that the configuration file doesn't get bundled into the client, which would pose serious security concerns.

**Comment by ctrlplusb** [comment]
On `next` branch.

Application configuration is at `/tools/config.js` now.

Environment configuration greatly simplified.

**Comment by ctrlplusb** [comment]
Thoughts @bkniffler @strues @enten @carsonperrotti ?

**Comment by strues** [comment]
Sounds great. Going to pull it down and check it out now. I'll let you know.

**Comment by strues** [comment]
Here Ive expanded upon what you've done with the configuration.  The idea being you can easily store configuration defaults for multiple environments. Let me know what you think.

```javascript

const config = {
  all: {
    env: process.env.NODE_ENV || 'development',
    // SSR enabled?
    ssrEnabled: true,

    // Configuration settings for the service worker.
    serviceWorker: {
      // Enable the service worker?
      // ... excluded for brevity
    },

    // Client bundle specific configuration.
    client: {
      // What should we name the json output file that webpack generates containing
      // details of all output files for a bundle?
      assetsFilename: clientBundleAssetsJSONFilename,
      // What is the public http path at which we must serve our client from?
      webRoot: clientBundleWebRoot,
    },

    // Server bundle specific configuration.
    server: {
      // The protocol for the server.
      protocol: envVars.SERVER_PROTOCOL || 'http',
      // ... excluded for brevity
    },

    // Development specific configuration.
    development: {
      // ... excluded for brevity
      vendorDLL: {
       // ... excluded for brevity
      },
    },
    paths: {
      buildOutput: buildOutputPath,
      clientBundle: clientBundlePath,
      // ... excluded for brevity
    },
  },
  production: {},
  staging: {},
};

module.exports = Object.assign({}, config.all, config[config.all.env]);
```

**Comment by ctrlplusb** [comment]
Awesome thanks @strues - I will review this in the morning.

**Comment by enten** [comment]
It's a complex topic (and I cry for the time that I will put to express awkwardly my thought).

First of all, we need to distinguish **two environment levels** (each corresponding to a distinct configuration level):
- a **concrete environment** used to act on webpack compilers configuration: it's the current user's environment state
- a **fake environment** used to act on runtime: it's the user's environment state when the build or hot build is made. 

In production environment, we shouldn't have to install dev dependencies. But we must be able to override the bundle configuration on runtime. Using [webpack.DefinePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin) to define global constants will break the user's environment influence.
So, on the server side: **we can override an `process.env` variable _under development environment only_**. Developers will be able to keep their own favorite configuration store to set up the runtime settings.
On the client side: its runtime configuration must be given by the server (with an inline javascript script tag for example).

I want to highlight that **it's important to exclude configuration variables specific to the bundles execution. It's the server responsibility to deal with runtime configuration and allow environment overrides**. 

Configuration settings like `ssrEnabled` and `http.protocol` mustn't figure in the configuration. Because **the configuration that we try to determine is a kind of meta-configuration**. That configuration must be **used to building bundles only**: not for change runtime behavior (except for development purposes but in that case, we use DefinePlugin to hack the runtime).

The **most settings in that meta-configuration are "static"** in the sense which they not often changed. The meta-configuration provide data used by webpack compilers (like `output.path`) and server bundles (like the path to the client assets). **Change the value of one of them setting will deeply affect the project structure and/or bundles output**. So I think it's not necessary to allow environment overrides in this meta-configuration level.

That being said, below is my suggestion.

```javascript
module.exports = {
  // server bundle
  server: {
    // target resolved as `node` target
    // by the webpackc onfig factory
    target: 'server',

    // path to the webpack config factory
    configFactory: './tools/webpack/configFactory',

    // path to the server source
    srcPath: './src/server',

    // path to the entry point (relative to `srcPath`)
    entryIndex: 'index.js',

    // path to the bundle output (webpack config `output.path`)
    outputPath: './build/server',

    // env vars defines by webpackDefinePlugin
    // used for development purposes only
    // we assume that the server handle runtime configuration
    // and environment overrides
    envVars: {
      SERVER_HOST: 'localhost',
      SERVER_PORT: 1337
    },

    // webpack-node-externals options
    nodeExternals: {
      // default to "./node_modules"
      modulesDir: './node_modules'
    }
  },

  // client bundle
  client: {
    // as like in server bundle
    target: 'web',
    configFactory: './tools/webpack/configFactory',
    srcPath: './src/client',
    entryIndex: 'index.js',
    outputPath: './build/client',

    // used as base URI and webpack config `output.publicPath`
    publicPath: '/client/',

    // path to static assets (favicon, robot.txt, etc)
    staticPath: './public',

    // webpack-dev-server options
    devServer: {
      port: 7331
    },

    // assets-webpack-plugin options
    assets: {
      // default to "assets.json"
      filename: 'assets.json',
      // default to `client.outputPath`
      path: './build/client'
    },

    // webpack-bundle-analyzer options
    analyzer: {
      analyzerPort: 8888
    },

    // dll configuration
    dll: {
      // default to false
      enabled: true,
      // default to "vendor"
      name: 'vendor',
      // default to ${dll.name}.js
      filename: 'vendor.js',
      // default to ${client.outputPath}/dlls
      outputPath: './build/client/dlls',
      // default to ${dll.outputPath}/${dll.name}.hash.json
      hashPath: './build/client/dlls/vendor.hash.json',
      // default to ${dll.outputPath}/${dll.name}.manifest.json
      manifestPath: './build/client/dlls/vendor.manifest.json'
      // additional paths to scan for catch imports
      sharedPath: ['./src/shared'],
      // packages excludes from dll
      excludes: ['**/*.css']
    }
  },
}
```

Each bundle property (`client` and `server`) will be passed in arg to the `configFactory` on build or hot build process. **We assume that the webpack configuration factory will compute a valid webpack config depending on the bundle given in arg.**

**Comment by cellis** [comment]
So, because i'm going to be using this in production with multiple live environments, my solution for this looks something like this:


```javascript
// tools/config/envVars.js
module.exports = function getEnvVarsForMode(mode) {...return env-<mode>...}
```

This way I can have multiple .env files (i.e. production,staging,hot-branch, whatever) and then deploy them.

**Comment by ctrlplusb** [comment]
Great feedback guys. I am going to incorporate something like this.

**Comment by ctrlplusb** [comment]
I guess one decision that needs to be made is whether we expose multi environment configurations (development/staging/production) like @cellis and @strues have suggested, or should we expect each host environment to be providing the necessary environment configuration (bootstrapped by a CI process or whatever).

My preference is for the later personally as I like the environment configuration to live with each host, but I am completely open to suggestions otherwise.

**Comment by ctrlplusb** [comment]
@enten 

Thanks for taking so much time to discuss this issue.  I really appreciate it!

> On the client side: its runtime configuration must be given by the server (with an inline javascript script tag for example). This is the server's job to not expose security settings to the client.

Should we not just have the DefinePlugin parse and provide the restricted/required environment variables for the client?  We could make them explicit then, and webpack ensures that are inlined for us.

---

So then in terms of the server.  We could move the call to `dotenv` within `/src/server/index.js`, which would allow bootstrapping of additional environment variables from a `.env` file that may exist within the executing environment.  Otherwise we expect the environment variables to have been provided to the executing process.

In my opinion we would then need do a parse of the environment variables, ensuring that the required values have been provided, and do error logging if they don't.

This then keeps the config file clean, and have it simply contain the required values for the build process.  One thing though, throughout the source we need to make references to various paths (for example the vendor DLL).  Do you think we should be providing these values via the DefinePlugin, which will inline them, or should the config file be referenced directly by the respective server source?

**Comment by code-punkt** [comment]
Great discussion.

If you decide to go the route that @strues sketched, be aware that sometimes `Object.assign` is not enough to merge default options with environmental options in case of webpack.

I've used [webpack-merge](https://github.com/survivejs/webpack-merge) to deal with that previously.

**Comment by enten** [comment]
The **server needs configuration settings for**...

* **the compilation process** (like the dll path, assets metadata file path, static resources path, ...). I suggest to call these setting "meta-configuration". **These settings _can't_ be changed after a build** (or hot build).

* **the runtime/executing process**. It's the standard configuration layer specific to each project (chosen by the developer). **These settings _can_ be changed after a build**. They can be grabbed from the environment, from a file inside the project or a file from the current user home's directory, a socket, a remote config store service, etc.

If we use **DefinePlugin** to manage runtime configuration settings: this will **break the environment influence on the execution** and we will **need dev dependencies under the production environment** to rebuild server and client bundles.

For these reasons, **we mustn't include runtime settings** in that configuration which we try specify.

The **client needs configuration settings for the runtime/execution process only**. The client bundle often targeting the web/browser environment. The browser don't know what is the `process` object (but the `window` object to infer lot of environment settings like `window.location`). Webpack allow to polyfill/mock the `process` object but I think that use it to store client configuration settings isn't the purpose. The main purpose of `process` object polyfill/mock is to make a piece of code universal and avoid reference errors. It's like mocking `window` object on server side to avoid reference errors (yes it's sadly exists) and use it to store runtime configuration settings.

> Should we not just have the DefinePlugin parse and provide the restricted/required environment variables for the client? We could make them explicit then, and webpack ensures that are inlined for us.

Well, what kind of configuration settings the client needs? It's often stuff like the Google Analytics public key or Recaptcha public key, the URL to the backend and so on. Even without SSR, it's the server responsibility to serve that configuration settings to the client. That runtime settings mustn't be hardcoded by the DefinePlugin. Because we need to allow environment influence without rebuilding step.

**The only exceptions that we can hardcode (with DefinePlugin) both on client and server bundles are some meta-configuration settings**: the server can receive all of them, but the client need a tiny part (put in the `process.env` mock/polyfill generally, like `ENV_NAME` or `IS_NODE`) for security reasons.

----

**In resume**:

* It's necessary to distinguish compilation (meta) configuration and runtime/executing configuration
* We mustn't mixed them into the same file
* We must let the developer choice how to handle the runtime configuration level but we suggest a solution baked in the boilerplate into the server sources (as current dot files, I have a preference for [rc](https://www.npmjs.com/package/rc) files)
* We must use DefinePlugin to hardcode compilation (meta) configuration (a little part of them for the client bundle)
* We can use DefinePlugin to hack the runtime for development purposes (like inject an environement variable to define the server port) according to the server runtime configuration implementation

**Comment by enten** [comment]
@ctrlplusb 
Have you considered [dotenv](https://www.npmjs.com/package/dotenv) for the runtime/executing configuration level instead of the current custom .env file implementation?

**Comment by ctrlplusb** [comment]
Yep.

> So then in terms of the server. We could move the call to dotenv within /src/server/index.js, which would allow bootstrapping of additional environment variables from a .env file that may exist within the executing environment. Otherwise we expect the environment variables to have been provided to the executing process.

😃

**Comment by ctrlplusb** [comment]
I think it is the way to go.

**Comment by ctrlplusb** [comment]
@enten @strues @bkniffler @carsonperrotti 

Released a new version of this on `next`.

Environment configuration is always resolved at runtime.

And have introduced a static configuration, babel config resolver and webpack config middleware.

All lives in `./config` folder.

Let me know your thoughts.

**Comment by enten** [comment]
@ctrlplusb 
As you said earlier on gitter: i'm happier with the current `next` config's format ([^21f6445](https://github.com/ctrlplusb/react-universally/tree/21f6445d9efeaebc9f920790cf000eb5c4e778f0)). Am I so predictable? Or too repetitive? :laughing: 

Firstly, I think there is a little mistake in [config/environement.js](https://github.com/ctrlplusb/react-universally/blob/21f6445d9efeaebc9f920790cf000eb5c4e778f0/config/environment.js):

```javascript
if (fs.existsSync(path.resolve(appRoot.get(), staticConfig.envFilePath))) {
  // --- dotenv.config();
  dotenv.config({
    path: path.resolve(appRoot.get(), staticConfig.envFilePath)
  })
}
```

And if I'm not mistaken, the **[config/environement.js](https://github.com/ctrlplusb/react-universally/blob/21f6445d9efeaebc9f920790cf000eb5c4e778f0/config/environment.js) object will be the same under `development` and `production` mode**, isn't it?

In addition, **we can't override these values with a file located outside the project's folder**.

Below my suggestion. Please note that I not encourage to allow the user to store the default `.env` file in a different path than the project root path. So in my suggestion, I used `envFileName` instead of `envFilePath`.

```javascript
// config/environment.js
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import appRoot from 'app-root-dir';
import staticConfig from './static';

// <+++>
import userHome from 'user-home';
import pkg from '../package.json';
// or
// const pkg = require(path.resolve(appRoot.get(), 'package.json'));
// </+++>

// <--->
// if (fs.existsSync(path.resolve(appRoot.get(), staticConfig.envFilePath))) {
//   dotenv.config();
// }
// </--->

// <+++>
const envName = process.env.NODE_ENV || 'development'
const envFile = staticConfig.envFileName // equals ".env"

;[
  path.resolve(appRoot.get(), envFile),
  path.resolve(appRoot.get(), `${envFile}.${envName}`),
  path.resolve(userHome, pkg.name, envFile),
  path.resolve(userHome, pkg.name, `${envFile}.${envName}`),
  path.resolve(userHome, '.config', pkg.name, envFile),
  path.resolve(userHome, '.config', pkg.name, `${envFile}.${envName}`)
]
  .filter((filePath) => fs.existsSync(filePath))
  .forEach((filePath) => dotenv.config({ path: filePath })
// </+++>

function getStringEnvVar(name : string, defaultVal : string) {
  return process.env[name] || defaultVal;
}

// ...
```

So, we can override values...

* by the environment mode with creating `.env.development` and/or `.env.production`
* and by files located outside the project folder with creating `~/${pkg.name}/.env` or `~/.config/${pkg.name}/.env`.

**Comment by ctrlplusb** [comment]
Great comments and advice as always @enten thank you!

I am doing another big update/parse of the configs and tools.  Making things more generic to allow for easier extension as suggested by @carsonperrotti.  I think its a worthwhile venture to allow for easier extensions of an api node bundle without expecting the adopter to hack the webpack config to bits.  I've managed to get the configs updated and have almost completed making the development tools a bit more generic to handle this.

I'll ping you all when I do the push.

**Comment by ctrlplusb** [comment]
@enten 

Just went through your environment file resolution strategy.  Really nice! 

I think I will integrate that. :)

**Comment by ctrlplusb** [comment]
@enten @carsonperrotti 

I've updated the configs, including the environment file resolution process.

@enten - do you think _all_ environment files should be ignored from github by default?

**Comment by ctrlplusb** [comment]
Thinking of renaming `config/static.js` -> `config/project.js`

**Comment by enten** [comment]
@ctrlplusb 

> do you think all environment files should be ignored from github by default?

It's a behavior banished from the opensource community. By contrast: this is quite common in enterprise repositories.

Sorry my good sir: i'm not an expert to give you an interesting answer.

So, I checked on other projects like the [official boilerplate](https://github.com/adonisjs/adonis-app) of [adonis framework](http://adonisjs.com/): there is an [.env.example](https://github.com/adonisjs/adonis-app/blob/develop/.env.example) only.

In my opinion, environment config used for test purposes (like `.env.test`) can be versioning (it's often a requirement to make CI working).

> Thinking of renaming config/static.js -> config/project.js

It's sound better.

**Comment by ctrlplusb** [comment]
Sounds good.  I'll update the documentation to inform the users of their options and state that it is up to them and their requirements on what route they would like to go down.  At least there is the option on persisting environment specific config should that be a need.

**Comment by williamoliveira** [comment]
So, what is the current concesual way of accessing env vars like API_URL on client code? as they are not exposed on `process.env` with DefinePlugin anymore

**Comment by ctrlplusb** [comment]
My recommendation is to pass these values via the server response. i.e. the html payload initialises a config object on the `window`.

e.g.

```html
<html>
  ...
  <body>
     ...
     <script type="text/javascript">
        window.CLIENT_CONFIG = {
          apiUrl: 'http://foo.bar.baz'
        }
     </script>
  </body>
</html>
```

**Comment by enten** [comment]
In my opinion, it's the server which must share the configuration with the client.

For example, you can serialize and write a configuration object from the server in window.clientConfig.

**Comment by williamoliveira** [comment]
But that will only work for client, so I'd need to write a helper func to fallback to process.env on SSR server?

**Comment by enten** [comment]
No, don't do that. Your server must have a configuration layer (a file which export a plain javascript object build from process.env for example).

Below an example.

```javascript
// src/server/config.js
export default {
  client: {
    api: process.env.CLIENT_API || 'http://localhost:3333/api'
  },
  // server private stuff
  jwt: {
    secret: 'supersecret!'
  }
}
```

```javascript
// src/server/middleware/reactApplication/index.js
// ...
import {client as clientConfig} from '../../config'

function reactApplicationMiddleware(request: $Request, response: $Response) {
  // ...

  const html = generateHTML({
    app,
    nonce,
    helmet: Helmet.rewind(),
    codeSplitState: codeSplitContext.getState(),
    clientConfig
  })

  // ...
}

export default (reactApplicationMiddleware : Middleware);
```

```javascript
// src/server/middleware/reactApplication/generateHTML.js

// ...

export default function generateHTML(args: Args) {
  const { app, initialState, nonce, helmet, codeSplitState, clientConfig } = args;
  // ...
  return `<!DOCTYPE html>
    <!-- ... -->
    <body>
      <div id='app'>${app || ''}</div>
      ${
        initialState
          ? inlineScript(`window.APP_STATE=${serialize(initialState)};`)
          : ''
      }
      ${
        clientConfig
          ? inlineScript(`window.CLIENT_CONFIG=${serialize(clientConfig)};`)
          : ''
      }
`;
}
```

So, you have the client configuration in `window.CLIENT_CONFIG` on client side. Be careful to not expose server secrets in the shared configuration.

**Comment by ctrlplusb** [comment]
@williamoliveira if you have a piece of code shared between the client and server bundles you can use the IS_SERVER or IS_CLIENT DefinePlugin flags to create bundle specific code blocks too.

Make any client bundle depend on the window.CLIENT_CONFIG like @enten and myself described, and any node/server bundle can use the project config files/envVars.

**Comment by williamoliveira** [comment]
So I'd have something like `(process.env.IS_CLIENT ? window : process.env).CLIENT_API` ?

**Comment by enten** [comment]
@williamoliveira 

On the server side: you use the default `src/server/config` export.
On the client side: you use `window.CLIENT_CONFIG`

In a shared code: **I recommend to not deal with the config object directly** (`src/server/config` or `window.CLIENT_CONFIG`) for security purposes but passe config values in function parameters.

An example (based on our previous example) with `axios` as http client.

```javascript
// src/shared/api.js
import axios from 'axios'
let api

export default api

export function initApi(baseUrl) {
  api = axios.create({
    baseUrl
  })
}
```

```javascript
// src/server/index.js
// ...
import {client as clientConfig} from './config'
import {initApi} from '../shared/api'

initApi(clientConfig.api)
```

```javascript
// src/client/index.js
// ...
import {initApi} from '../shared/api'

initApi(window.CLIENT_CONFIG.api)
```

**Comment by williamoliveira** [comment]
Got it, nice approach
Just, could you elaborate on the security point?

**Comment by enten** [comment]
If you accidentally import `src/server/config` in a `src/shared/**/*.js` file: you potentially expose the entire config server content in the client bundled sources.

Nobody wants to expose server config secrets in the client sources.

**Comment by ctrlplusb** [comment]
@enten @williamoliveira 

By default the client bundle config is set to not include the config folder for bundling, so if you accidentally do import the configs it should fail.  The failure will be at runtime I believe as you will just get "undefined" anywhere you imported a config file.

**Comment by enten** [comment]
@ctrlplusb 

Below a simple strategy to deal with server runtime configuration.

```javascript
// src/server/config.js
module.exports = {
  client: {
    gaPublicKey: 'xyz',
    locales: ['en', 'fr']
  },
  // server secrets
  backendApiUrl: 'http://secret-host:3333/api/v1',
  backendApiKey: 'abcef',
  // ...
}
```

```javascript
// src/server/middleware/reactApplication/index.js
// ...
import {client as clientConfig} from '../../config'

function reactApplicationMiddleware(request: $Request, response: $Response) {
  // ...

  const html = generateHTML({
    app,
    nonce,
    helmet: Helmet.rewind(),
    codeSplitState: codeSplitContext.getState(),
    clientConfig
  })

  // ...
}

export default (reactApplicationMiddleware : Middleware);
```

```javascript
// src/server/middleware/reactApplication/generateHTML.js
// ...
export default function generateHTML(args: Args) {
  const { app, initialState, nonce, helmet, codeSplitState, clientConfig } = args;
  // ...
  return `<!DOCTYPE html>
    <!-- ... -->
    <body>
      <div id='app'>${app || ''}</div>
      ${
        initialState
          ? inlineScript(`window.APP_STATE=${serialize(initialState)};`)
          : ''
      }
      ${
        clientConfig
          ? inlineScript(`window.CLIENT_CONFIG=${serialize(clientConfig)};`)
          : ''
      }
`;
}
```

```javascript
// src/shared/config
let config
if (process.env.IS_NODE) {
  config = require('../server/config').client
} else {
  config = JSON.parse(window.CLIENT_CONFIG)
}
module.exports = config
```

```javascript
import {locales} from './shared/config'
// ...
```
