### ISSUE TITLE
file-loader doesn't inline assets

### ISSUE THREAD

**Issue by adamcavalli** [ctrlplusb/react-universally#215]
On the next branch (but not master) in configFactory.js, file-loader is used instead of url-loader. The limit parameter is not respected by file-loader, so assets below the size limit will not be inlined.

https://github.com/webpack/url-loader
https://github.com/webpack/file-loader

While you're in that portion of the code, it may be worthwhile to add common extensions for audio/video files.
/\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$/

**Comment by ctrlplusb** [comment]
Appreciate the heads up and the suggestion. :)

**Comment by ctrlplusb** [comment]
Hi @adamcavalli 

After some consideration I have decided that it is better to use the `file-loader` rather than the `url-loader` by default.  Inlining assets puts extra burden on the JS thread, where the browser could do parallel pulls of asset URLs.

I think it is better to keep things simple and let adopters of the starter kit decided where and when they would like to inline assets.

**Comment by ctrlplusb** [comment]
I'll update the dependencies and configs appropriately.

**Comment by ctrlplusb** [comment]
On `next`.
