### ISSUE TITLE
Feature - React Intl

### ISSUE THREAD

**Issue by maximblack** [ctrlplusb/react-universally#254]
I have working Internationalization solution based on "react-intl". I can create a pull request of it in master branch or we can create a new branch for "intl"

**Comment by LorbusChris** [comment]
I'm highly interested in this. Please create a PR, even @ctrlplusb decides against maintaining an intl branch here, this may be very helpful for reference!

**Comment by enten** [comment]
I'm working on a boilerplate with react-intl support.
Below links to some code. I hope these files may will help you.

* [src/shared/utils/intl.js](https://github.com/enten/reduction/blob/master/src/shared/utils/intl.js): some intl util functions
* Using [`locale` middleware](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/server/index.js#L28) in express to determine the best locale on server side
* [Getting locale data on each request](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/server/ssr/index.js#L21) before start the server side rendering
* On client side, we need to [polyfill intl API if it's needed](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/client/app.js#L20) and [register locale determined by the server](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/client/app.js#L21) BEFORE [first client side rendering](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/client/app.js#L27)
* Easy to change locale AFTER first client side rendering: [get locale data of a specific locale ](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/shared/reducers/intl.js#L28) and don't forget to [register](https://github.com/enten/reduction/blob/master/src/shared/utils/intl.js#L43) [this change](https://github.com/enten/reduction/blob/5a0d41fdaa89035dfdc2e545d1fa1a9d19ebd90a/src/shared/reducers/intl.js#L30)

In extra: a [script to extract and manage](https://github.com/enten/reduction/blob/master/scripts/extract-intl.js) [translations](https://github.com/enten/reduction/tree/master/src/translations) from the source code.

**Comment by carsonperrotti** [comment]
Thanks for the detailed comment @enten.

**Comment by ctrlplusb** [comment]
Awesome guys.  I would love to see this too.

**Comment by enten** [comment]
@maximblack 

Be careful with **[`react-intl`](https://github.com/yahoo/react-intl) and [`intl`](https://github.com/andyearnshaw/Intl.js) modules**: their usage **can considerably increase compilation times** of the client and server bundles. 

This increase is due to the locale-data files of the both modules (`intl/locale-data/*` and `react-intl/locale-data/json(p)?/*`).

### Browser side

On the browser side: we need to bundle the locale-data files into chunks.
**Including locale-data files in the DllPlugin allow to reduce re-compilation times on dev mode.**
It's not possible for the moment but there is a discussion about [allowing to manually add modules in the DllPlugin](https://github.com/ctrlplusb/react-universally/issues/257).

### Server side

On the browser side: we need to explicitly exclude the locale-data files (avoid chunk creation for each translation files).
[Use `webpack-node-externals`](https://github.com/ctrlplusb/react-universally/blob/543a69e27a73fbd64159b9f03a3d8d12c53a67d4/tools/webpack/configFactory.js#L91) allow to don't create chunks for node_modules imported.

Great. **But when webpack meet uses of `require()`/`System.import()` with an expression** (like [`const localeData = require(`react-intl/locale-data/${locale}`)`](https://github.com/enten/reduction/blob/20afcfa1ed8cb92589d4262873026275eda3a206/src/shared/utils/intl.js#L44)): **a chunk file will be created for each file which match the expression** (note: webpack `externals` has no effect on this behavior).

The `webpack.IgnorePlugin` (used as below for example) seems to be able to solve this issue. I need to make tests to verify that.

```javascript
new webpack.IgnorePlugin(/(react-)?intl\/locale-data/)
```

**Comment by enten** [comment]
**Finally, I recommend the approach below to avoid increasing compilation times.**

As a reminder: the source of this increase.

> when webpack meet uses of `require()/System.import()` with an expression (like `const localeData = require(react-intl/locale-data/${locale})`): a chunk will be created for each file which match the expression

In my case: the function below force webpack to create a chunk for each translation files in `intl/locale-data/jsonp/` and `react-intl/locale-data/`.

```javascript
// src/shared/utils/intl.js
export function polyfillIntlApi(locale) {
  return System.import('intl')
    .then(() => System.import(`intl/locale-data/jsonp/${locale}`))
}
export function registerLocaleData(locale) {
  const localeData = require(`react-intl/locale-data/${locale}`)
  addLocaleData(localeData)
}
```

So, translation files of all locales will be bundled: this is clearly NOT what we want.
**To avoid this behavior easily: I copied all locale files which my app needs into my project source code.** and update my expression imports as below.

```javascript
// src/shared/utils/intl.js
export function polyfillIntlApi(locale) {
  return System.import('intl')
    .then(() => System.import(`../../locale-data/intl/${locale}`))
}
export function registerLocaleData(locale) {
  const localeData = require(`../../locale-data/react-intl/${locale}`)
  addLocaleData(localeData)
}
```

Translations files will be bundled (on server and browser side) but it's not a real issue: because this not increase compilation times anymore.

So we don't need to include translation files in the dll on client side and ignore them on server side.

### Extra

Below the function `createLocaleDataFiles(outputPath, locale)` which can be used to create npm's script which call it for each locale needed by the application.

```javascript
// usage example

;['en', 'fr'].forEach((locale) =>
  createLocaleDataFiles('./src/locale-data', locale)

// output:
//
// en
//   intl
//     ./node_modules/intl/locale-data/jsonp/en.js
//       > ./src/locale-data/intl/en.js
//   reactIntl
//     ./node_modules/react-intl/locale-data/en.js
//       > ./src/locale-data/react-intl/en.js
// fr
//   intl
//     ./node_modules/intl/locale-data/jsonp/fr.js
//       > ./src/locale-data/intl/fr.js
//   reactIntl
//     ./node_modules/react-intl/locale-data/fr.js
//       > ./src/locale-data/react-intl/fr.js
```

```javascript
const fs = require('fs')
const {dirname, resolve: resolvePath} = require('path')

module.exports = function createLocaleDataFiles (outputPath, locale) {
  console.log(locale)

  const localeInputPaths = getLocaleInputPaths(locale)
  const localeOutputPaths = getLocaleOutputPaths(outputPath, locale)

  ensureDirExists(outputPath)
  
  ;['intl', 'reactIntl']
    .forEach((key) => {
      console.log(' ', key)
      console.log('   ', localeInputPaths[key])
      console.log('      >', localeOutputPaths[key])

      ensureDirExists(dirname(localeOutputPaths[key]))
      copyFile(localeInputPaths[key], localeOutputPaths[key])
    })
}

function copyFile (sourcePath, targetPath) {
  return fs.writeFileSync(targetPath, fs.readFileSync(sourcePath))
}

function ensureDirExists (path) {
  if (!fs.existsSync(path)) {
    fs.mkdirSync(path)
  }
}

function getLocaleInputPaths (locale) {
  const dashPos = locale.indexOf('-')
  const baseLocale = ~dashPos ? locale.substring(0, dashPos) : locale
  return {
    intl: require.resolve(`intl/locale-data/jsonp/${locale}`),
    reactIntl: require.resolve(`react-intl/locale-data/${baseLocale}`)
  }
}

function getLocaleOutputPaths (outputPath, locale) {
  return {
    intl: resolvePath(outputPath, 'intl', `${locale}.js`),
    reactIntl: resolvePath(outputPath, 'react-intl', `${locale}.js`),
  }
}
```

**Comment by kvnsw** [comment]
Thanks for sharing the implementation @enten! Would really love seeing this as a branch of the repo.

**Comment by ctrlplusb** [comment]
Closing this, as per discussion we are going to keep feature branches down to a minimum.  This will still be a helpful reference though, so thanks guys!

**Comment by oyeanuj** [comment]
@enten @maximblack Do one of you by any chance have an up to date (with current `react-universally`) version of this integration? If not, what fork would have the latest? Much appreciated, thanks!
