### ISSUE TITLE
[redux] Client executes prefetchData & deferredData for every task route

### ISSUE THREAD

**Issue by AndreasZeiser** [ctrlplusb/react-universally#255]
Hey!

The `executeTasks` function in `executeTasks.js` executes both task types for every task route. Bothe tasks are executed because `window.APP_STATE` is deleted with every route change, so the first conditions is always false:

```javascript
const tasksToExecute = window && window.APP_STATE
  // We have an APP_STATE available, which will contain the state from the
  // server populated by any 'prefetchData' tasks, therefore we only need to
  // call the 'deferredData' tasks.
  ? ['deferredData']
  // No data is available so we will execute both the 'prefetchData' and
  // 'deferredData' tasks.
  : ['prefetchData', 'deferredData'];

  if (window) {
    // We now remove the APP_STATE as it has been safely merged into the redux
    // store at this stage, and by deleting it we can make sure that we will
    // execute both the 'prefetchData' and 'deferredData' tasks for every route
    // change that happens on the client side.
    delete window.APP_STATE;
  }
```

The comment in the second condition implies that this behavior is desired. I just can't think of a case in which it is required to execute `prefetchData` because `prefetchData` is described as a task for the server. Am I missing something?

**Comment by ctrlplusb** [comment]
Hey @AndreasZeiser;

Sure thing, hopefully I can shed some light on this reasoning...

Imagine you had the following routes, each with a `prefetchData` and `deferredData` task attached:

 - /foo
   - prefetchData: () => ...
   - deferredData: () => ...
 - /bar
   - prefetchData: () => ...
   - deferredData: () => ...
   
Try to visualise the following workflow:

__Client -> Server -> Client__

1.   You make a request to the server for "/foo".
     The server analyses the route, finds a `prefetchData` task, fires it, and attaches the resultant state to the response via the `window.APP_STATE` assignment inline script.
2.   On the browser your React app loads for the first time.
     The React app sees the state given to it by server and initialises the redux store.
     Your app initialises.
     It then analyses the route, finds a `deferredData` task, fires it.

You application now has all the data you desired for the "/foo" route loaded into the Redux store.

But now what should happen if you switch to the "/bar" route on the client? e.g. by clicking `<Link to="/bar" />`. This results in a __Client -> Client__ interaction in which the server is not involved. 

The server is no longer responsible for loading the route and its data, which means that `window.APP_STATE` will not contain the required `prefetchData` results for the "/bar" route.  This data is obviously important to the route in question, therefore we need to make sure we execute this task when switching routes on the client (along with any `deferredData` task that may exist). 

Note: A _Client -> Client_ interaction isn't the only case in which we won't have the required `prefetchData` for a route.  What if we switched off server side rendering? This means that `window.APP_STATE` would never have existed. Therefore We can make a safe assumption in saying: if a `window.APP_STATE` does not exist then we should execute both the `prefetchData` and `deferredData` tasks for a route.

We know the server is responsible for setting the `window.APP_STATE` global and this data is only representative of the very first route initialised on the client, therefore, we can consume and delete this data after the first data tasks parse.  We then know that any subsequent route changes will need to executed both the `deferredData` and `prefetchData` tasks for the respective routes in order to get the required data for them.

---

Does that make a bit more sense? 

I may need to work on this documentation a bit so if you find anything confusing please point it out and I will be happy to do some revisions. :)

**Comment by ctrlplusb** [comment]
Another note on this.  I haven't done so in the example implementation but you should consider your data loading strategies carefully.  You could for example put a caching layer within your `redux-thunk` (or whatever else) implementation to prevent unnecessary HTTP requests.  

Of course there is no blanket answer for this.  Every application and case needs to be taken into consideration applying the most appropriate solution.

**Comment by ctrlplusb** [comment]
Really `prefetchData` and `deferredData` should be renamed to something a bit more revealing.  Their inconsistent tense doesn't help either.

**Comment by AndreasZeiser** [comment]
Thank you @ctrlplusb for the detailed response. Your example of the workflow makes completely sense and I do understand and love the idea behind task routes. 

For me the source of confusion is the following part of the documentation:

> Within this project we are using this mechanism to define all of the routes which require data to be loaded. We have preconfigured two different task types to help with this:
> 
> * prefetchData: This is a task that should be executed before we do any rendering on the server.
> * deferredData: This is a task that should be executed on the client for any matched routes.
>
> All tasks have to return a Promise, which gives us the capability to know when the task has completed.
> 
> Using this we can then fire all our prefetchData tasks on the server, which in this project fires redux-thunk actions that return promises. We then wait for the promises to complete, after which we can safely assume that we have fetched all the data required for the components we expect to mount against the location.

It basically says that `prefetchData` runs _only_ on the server but it actually must say that `prefetchData` runs on the server _only for the initial request_ and runs then on the client for any matched route as well.

Before updating the docs to be more specific about the inner workings of `prefetchData` and `deferredData` I would like to raise the question whether or not `deferredData` is required. `prefetchData` is the task responsible for fetching the data on the server (initial request) and the client (consecutive requests). However, I struggle to find any use cases for `deferredData`. What are your use cases for `deferredData`? The documentation has also no example for `deferredData` which gives an indication that it _might_ be not that important.

I think that if we can keep the task routes simple by having only one task running for every matched route regardless of where this task runs (server or client) we thereby make the whole thing much easier to understand. 

What do you think? I would be happy to help with that implementation.

**Comment by ctrlplusb** [comment]
Some good points about keeping things simple, which I am always up for.  I am letting a few thoughts boil on this.  Will get back to you. :)

**Comment by ctrlplusb** [comment]
I have been dreaming up a much simpler and nicer API.  Just did a bunch of research on the phone whilst patting my daughter to sleep. 😀
I definitely feel what I am is possible. It will bring collacation of tasks with components (i.e. our react router v4 routes) and will completely kill any need for a prefetch/deferred model. 😀
Stay tuned in the new year.. . 😀

**Comment by strues** [comment]
I started writing something for RR4 to handle data fetching, but ended up back on RR3. Hoping sometime between Christmas and New Years to have some time to give away to RR4.

**Comment by ctrlplusb** [comment]
Awesome to hear @strues!

**Comment by elodszopos** [comment]
I see a good use-case for `deferredData` for pre-loading data for next possible actions that the user can do. Will need a little work though.

**Comment by ctrlplusb** [comment]
Hey all

You can track progress of the new library I am developing to help with data load/defer/SSR needs here:

[`react-jobs`](https://github.com/ctrlplusb/react-jobs)
