### ISSUE TITLE
Simplify configuration management and retrieval

### ISSUE THREAD

**Issue by amcsi** [ctrlplusb/react-universally#259]
I'm using v10 and am having trouble accessing custom variables in my shared components.

Previously in v9 I had to make sure the environment variable was in the whitelist and that the environment variables be set in the .env file or be part of the environment of the process on build time, then they would be available when running.

Here in v10 apparently there's no whitelist anymore, and supposedly environment variables are determined on start rather than build. And I can access the environment variables as process.env.* if they are in the .env file, none are available that were defined for the process.

**Comment by smirea** [comment]
you should be able to add any vars you want to the `webpack.definePlugin` section in `configFactory.js`

This is what's currently there:

```js
new webpack.DefinePlugin({
        // Adding the NODE_ENV key is especially important as React relies
        // on it to optimize production builds.
        'process.env.NODE_ENV': JSON.stringify(mode),
        // Is this the "client" bundle?
        'process.env.IS_CLIENT': JSON.stringify(isClient),
        // Is this the "server" bundle?
        'process.env.IS_SERVER': JSON.stringify(isServer),
        // Is this a node bundle?
        'process.env.IS_NODE': JSON.stringify(isNode),
      }),
```

anything you add in there should be accessible in shared on both client and server

**Comment by amcsi** [comment]
@smirea I have tried that just now and it seems that's done on build time rather than run time.

That seems to go against what's in the [changelog](https://github.com/ctrlplusb/react-universally/blob/master/CHANGELOG.md#1000---2016-12-08) "Environment variables have been dramatically simplified in way. They are no longer used at build time, but rather at run time, giving you a greater degree of flexibility."

**Comment by LorbusChris** [comment]
Instead of on the whitelist, you have to register any env var you want to use in `config/private/environment.js`:

```
// Ensure that we first register any environment variables from an existing
// env file.
registerEnvFile();

export default {

  // Your custom env vars go here (with defaults)

  // The host on which the server should run.
  host: getStringEnvVar('SERVER_HOST', 'localhost'),
  // The port on which the server should run.
  port: getIntEnvVar('SERVER_PORT', 1337),
  // The port on which the client bundle development server should run.
  clientDevServerPort: getIntEnvVar('CLIENT_DEVSERVER_PORT', 7331),
};
```

I agree that documentation on this is a bit scarce, I also stumbled over this at first.

**Comment by ctrlplusb** [comment]
Hey all;

Okay, I can definitely see that this part of the system needs for more documentation and examples than there currently are.  We've had a few discussions about this spread across various of the issues.

I'll try collate all of our thoughts into a helpful documentation section.

Also, I am going to fabricate an example of shared state across the client/server.

**Comment by strues** [comment]
Tagging off of @ctrlplusb's last comment. We should setup an online working example. Additionally, setup a branch and start writing some documentation. Or there's GitBook. I'm not too familiar with GItBook but it might be over kill?

**Comment by ctrlplusb** [comment]
Related #206 

@enten breaks down some strategies within that issue.

**Comment by enten** [comment]
@ctrlplusb 

Thanks sir! You know well that I like to talk about this deeply recurrent topic.

So, below my current approach which is an improvement of [the one described here](https://github.com/ctrlplusb/react-universally/issues/206#issuecomment-266605200) in #206.

But before: we need to understand our previous approach's benefits and its weakness.

> As reminder in `react-universally`'s master branch: we try to be simple as possible to don't restrict the developer in their choices to improve or replace a component. But we need to suggest simple strategies and implementations which are aware from security issues. Maybe they will be useless for some developers. But in our philosophy: we can't share stuff with potential security issues.

### Previous approach's benefits

It's needed to remind and highlight the **benefits of the previous approach**:

* the **server is responsible of sharing the runtime config to the client** (by writing it in `window.CLIENT_CONFIG` in our example)
* so, we can **control the config properties shared with the client**
* writing client config into `window.CLIENT_CONFIG` **allow to customize the shared config according to the http request** (add more stuff if the user who made the request is an admin for example)
* the **developer is free to use a configuration store module** (like [confippet](https://github.com/electrode-io/electrode-confippet), [config](https://www.npmjs.com/package/config), [confit](https://github.com/krakenjs/confit), etc) than our basic implementation

**The main benefit and purpose of our previous approach is to don't include the entire server config in the client bundle.** We achieve that by let the server implement and decide how and which config stuff will be share with the client.

### Previous approach's code snippets

```javascript
// src/server/config.js
const config = module.exports = {
  client: { // <-- THIS CAUSE THE WEAKNESS
    gaPublicKey: 'xyz',
    locales: ['en', 'fr']
  },
  // server secrets
  backendApiUrl: 'http://secret-host:3333/api/v1',
  backendApiKey: 'abcef',
  // ...
}
```

```javascript
// src/server/middleware/reactApplication/index.js
// ...
import {client as clientConfig} from '../../config'

function reactApplicationMiddleware(request: $Request, response: $Response) {
  // ...
  const html = generateHTML({
    app,
    nonce,
    helmet: Helmet.rewind(),
    codeSplitState: codeSplitContext.getState(),
    clientConfig
  })
  // ...
}

export default (reactApplicationMiddleware : Middleware);
```

```javascript
// src/server/middleware/reactApplication/generateHTML.js
// ...
export default function generateHTML(args: Args) {
  const { app, initialState, nonce, helmet, codeSplitState, clientConfig } = args;
  // ...
  return `<!DOCTYPE html>
    <!-- ... -->
    <body>
      <div id='app'>${app || ''}</div>
      ${ // <-- SHARE THE CONFIG TO THE CLIENT IN window.CLIENT_CONFIG
        clientConfig
          ? inlineScript(`window.CLIENT_CONFIG=${serialize(clientConfig)};`)
          : ''
      }
`;
}
```

```javascript
// src/shared/config
let config
if (process.env.IS_NODE) {
  config = require('../server/config').client
} else {
  config = window.CLIENT_CONFIG
}
module.exports = config
```

### Previous approach's weakness

**The weakness of the previous version of that strategy is to expose only the client config in the shared code.** It's due to the choice made of distinguish server/client config properties by isolating the client stuff in the `client` property of the server config.

**That choice is definitely wrong** because:

* we **can't access in the shared code of the server properties**
* it's **hard to deal with computed properties** as below for example

```javascript
config.baseurl =
  ('http' + (config.ssl ? 's' : '') + '://') +
  (config.host || '127.0.0.1') +
  (!~[443, 80].indexOf(config.port) ? ':' + config.port : '')
```

### New simply approach

If you think that the next approach will break your code: please keep calm because we also want to avoid break changes.

**The next approach change the way to write the server configuration file: we will made a smart use of [Object.defineProperties()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties)** If you don't familiar with it: please take few minutes to read the doc (it's a requirement to understand the next code snippets).

Yep, I made the choice to **use [Object.defineProperties()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) instead of property's [getter/setter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters) because we want to be able to choice the visibility of a property with the `enumerable` descriptor property** (and may have possibility to choice if a property will be `configurable` or/and `writable` but they won't in most case).

The use of [Object.defineProperties()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) offer few benefits:

* **Never share accidentally a config property to the client** because the default `enumerable` descriptor property value is `false`: so we need to explicitly **set `enumerable` to `true` to share a config property with the client**
* **Deal with computed property easily** thought the use of `get`/`set` descriptor properties
* We don't need anymore to isolate the client config stuff in a `client` property
* **Have the complete server configuration in shared code on the server side but only the parts needed by the client on server side**
* Pretty one line declaration syntax (okay it's not a real benefit but we all like clean code, no?)

Below an example of the server config using `Object.defineProperties()`

```javascript
// src/server/config.js
const config = Object.defineProperties({}, {
  publicKey: {
    enumerable: true,
    value: 'value of the publicKey will be shared with the client'
  },
  privateKey: {
    enumerable: false, // <-- default value should be false but it's more safer to set it
    value: 'value of the privateKey will not be shared with the client'
  },
  publicKeyComputed: {
    enumerable: true,
    get: () => {
      // we can use another property like: config.publicKey
      return 'public computed value'
    }
  },
  privateKeyComputed: {
    enumerable: false,
    get: () => {
      return 'private computed value'
    }
  },
  // ...
})

module.exports = config
```

We also need to make little adjustments for sharing the config from the server to the client.

```javascript
// src/server/middleware/reactApplication/index.js
// ...
// import {client as clientConfig} from '../../config' // << ---
import config from '../../config' // << +++

function reactApplicationMiddleware(request: $Request, response: $Response) {
  // ...
  const html = generateHTML({
    app,
    nonce,
    helmet: Helmet.rewind(),
    codeSplitState: codeSplitContext.getState(),
    clientConfig: config // << +++
  })
  // ...
}

export default (reactApplicationMiddleware : Middleware);
```

> Notes:
> * we pass all the config but we can filter the config or add more stuff according to the request data
> * `serialize-javascript` (which is used to serialize our object to plain text) won't serialize no enumerable properties
> * but if you want to be sure to give client properties only to `generateHTML()`, you can do the next trick: `clientConfig: JSON.parse(JSON.stringify(config))`

We finish with a tiny adjustment in our shared config (to have the full server config on server side):

```javascript
// src/shared/config
let config
if (process.env.IS_NODE) {
  // config = require('../server/config').client // < ---
  config = require('../server/config') // < +++
} else {
  config = window.CLIENT_CONFIG
}
module.exports = config
```

Voilà!

**Comment by ctrlplusb** [comment]
Very clever @enten!

**Comment by ctrlplusb** [comment]
Hmmm, lots of food for thought here.

I am considering doing a massive "simplify simplify simplify" parse on the config folder.  It's way too complicated.

Current ideas: 
  - drop the plugins.js - put it in the configFactory.  It's very webpack specific and I don't think it has enough value to warrant the extra complexity.
 - kill the private/public folders.
 - merge environment variable resolution into a single config file (they will still be interpreted at runtime), but it's one less import.
 - look at a "shared/client" config strategy.  I like @enten's approach but it might be too clever to begin with.  I have another idea to start with and we can work from here.

The new config folder would look like:
```
 |- config
    |- private.js
    |- shared.js
```

Yes, this is a breaking change, but I don't anticipate it being difficult to migrate existing code to.  The massive simplification may be valuable to users. 

I also plan to include A LOT of documentation and proper examples of using values in the shared code.

**Comment by ctrlplusb** [comment]
Simplified things even further...

```
 |- config
    |- index.js    // Exposes functions to get config values and provide client state to html.
    |- values.js  // ALL the configuration values (client/server/environment) merged.
```

Came up with a useful util function that allows you to read config values.  This allows you to avoid having to thing what context you are in and exactly how you should be calling the config values.  

All you have to do is update the `values.js` with the settings you would like to expose and then use the same `get` function API everywhere.

**Comment by ctrlplusb** [comment]
Ok, the new API is awesome.  No more worrying about context.  No more importing 3 different configuration files.

ALL configuration is accessed via the following API:

```js
import { get } from '../config';

console.log(get('host'));
console.log(get('serviceWorker', 'enabled'));
```

We take of all the boilerplate for you.  All you need to worry about is setting the values up in `./config/values.js` appropriately.

I have put a ton of guard/checks that throw helpful error messages as there are now magic strings being passed around.  They seem to work well, I am really enjoying the new read API.

This change touches so many files and is a complete rethink of configuration I am going to have to declare this a major release bump.

I have just pushed the code changes to `next` I would appreciate it if you guys could give it a try and see if it is a more accessible API.

**Comment by ctrlplusb** [comment]
@amcsi @smirea @LorbusChris @strues @enten

**Comment by amcsi** [comment]
So basically the experience I am to expect is that I freely use process.env.* values defined on run time in the config.js files, and then in client code I would just import the config itself? That would indeed sound really simple.
I'm not sure about the `get` config accessor though. It seems like you're providing an unnecessary tool and violating SRP. With this you would also remove the ability to use types in the config with the help of Flow, because ˙get()` couldn't possibly guarantee any value other than `any`. Although I'm a bit new to Flow so I might be wrong about something.

By the way I'm working with the Redux branch of this project, so I won't be able to try it out in my current project without the Redux bit.

**Comment by ctrlplusb** [comment]
> It seems like you're providing an unnecessary tool and violating SRP.

Please explain. :)

> With this you would also remove the ability to use types in the config with the help of Flow.

Unfortunately you are right. In this case I have exchanged type safety with simplicity. I am going to still play around with this in the hope that we can get at least some Flow help, but as a backup we do have preconditional checks.

**Comment by amcsi** [comment]
SRP as in Single Responsibility Pattern. Although mainly a rule of thumb in OOP languages, basically it means that the config itself shouldn't be responsible for providing an unnecessary accessor for the values by default. If you want to provide such a tool, then perhaps a separate js file could provide it (`get()`), wrapping the config.

**Comment by ctrlplusb** [comment]
Cool, no I got that you meant Single Responsibility Pattern, I just wanted to know how you thought it was being violated.  :)

The config values are all contained within `./config/values.js`.
The helpers (i.e. `get`) are contained within `./config/index.js`.  They then call into the values appropriately. :)

Ok, an update in regards to the Flow type safety. 

If I change the API to the following we can get flow type checking with autocomplete still:

```js
console.log(get(c => c.serviceWorker.enabled));
```

As opposed to `get('serviceWorker', 'enabled')`.

Do you think this is better?

**Comment by amcsi** [comment]
OK I think I was assuming that index.js has the public values and values.js had the public and private ones and you just tossed in an accessor function as well. So apparently values has all the values.
I don't quite understand. Is there no way to make it so that the config values could be used in the client without an accessor function?

**Comment by ctrlplusb** [comment]
Argh, I just wrote a massive doc on this and then my browser went "back" and lost it all.

**Comment by amcsi** [comment]
:(:(
Next time I highly suggest this fantastic browser plugin: https://chrome.google.com/webstore/detail/lazarus-form-recovery/loljledaigphbcpfhfmgopdkppkifgno

**Comment by ctrlplusb** [comment]
Okay, let me try this again...

After some period of using this project we have come to establish the following goals for the configuration.

 - __Easy to use__
   I really want this starter to be easy for people to understand and adopt.  If it fails in this regard then the project fails.
 - __Centralised__
   It's much nicer and easier to have a centralised configuration.  This will help the project scale.
 - __Secure__
   We want the configuration secure by default.  The last thing you want are database connection strings being sent across the wire with your client bundle.
 - __Allows for build and execution time configuration.__
   As your project scales across environments having the ability to provide configuration at execution time becomes exceedingly useful.

There are a few solutions that could be considered to solve some/all of these goals:

---

__Option 1:__ _DefinePlugin_

We could use Webpack's DefinePlugin to substitute configuration value usage throughout our source.  These values could be read from a central location (environment vars or a config file).

e.g.

```js
app.listen(process.env.PORT, () => console.log('Running'));
```

This option satisfies the following goals:

  - Easy to use
  - Centralised
  - Secure

It fails the following goals:

  - Allows for build and execution time configuration
    As DefinePlugin is interpreted at build time, the values get baked into our bundles and we then don't have a solution to allow for execution time provided values without adding on additional features to the project.  Adding additional features would then affect the "ease of use" and possibly "centralisation" goals.

---

__Option 2:__ _config.js file_

We could create a `config.js` that holds all our configuration values, and then simply import this file using the configuration values whereever we need them.

e.g.

```js
import config from './config';
app.listen(config.port, () => console.log('Running'));
```

This option satisfies the following goals:

  - Easy to use
  - Centralised

It presents difficulties with the following goals:

  - Secure
    If you import the `config.js` file into the shared or client source code then webpack will end up bundling the configuration values with your client bundle.  We would have to use some clever mechanisms within the config file to ensure that sensitive values are stripped away from client bundles.

It fails the following goals:

  - Allows for build and execution time configuration
    This file is interpreted at build time and bundled into the server/client.  A client bundle can't maintain a handle on the server's environment variables so there is no way to provide execution time configuration.

---

__Option 3:__ _values.js with helper functions_

This option expands on option 2 to solve the goals it failed to achieve.

How do we get execution time configuration (environment variables) to the client code?  The server is responsible for interpretting environment variables, therefore it must be the server's responsibility to send them to client.  Within the HTML response from the server we could include something similar to:

```js
const htmlResponse =
  `<html>
    <head>...</head>
    <body>
      ...
      <script type="text/javascript">
        window.CONFIG_VALUES = {
          foo: ${process.env.FOO},
          bar: ${process.env.BAR},
        }
      </script>
    </body>
  </html>`;
```

Now we know that our client code can access these execution time configuration values by doing `window.CONFIG_VALUES.foo` for example.

This works, however, it breaks some of the goals of our project (easy of use, centralised).  It is especially harmful to our shared source as you need to do all sorts of checks to know if the code is being executed on the server or in the browser.  If it is on the server you need to do `process.env.FOO` whilst in the browser you should use `window.CONFIG_VALUES.foo`;

Here is an example of how messy this can get:

```js
let foo;
if (process.env.IS_NODE) {
  // webpack will only include this block of code on the server.
  foo = process.env.FOO;
}
if (process.env.IS_CLIENT) {
  // webpack will only include this block of code on the client.
  foo = window.CONFIG_VALUES.foo;
}
```

That code lacks guards and other bits to make your code more reliable, but it is already an eye sore.  It requires you to do context switching any time you want to access config values in your code.

To avoid all of this we provide two helpers.  The first one creates a configuration object script for your HTML response so that you don't need to do any of this manually.

```js
import { clientConfigScript } from '../config';

const htmlResponse =
  `<html>
    <head>...</head>
    <body>
      ...
      <script type="text/javascript">
        ${clientConfigScript()}
      </script>
    </body>
  </html>`;
```

Then the second one provides you with a unified API to access configuration values, no matter which bundle (client/server) the code you are writting will land up in.

```js
import { get } from '../config';
const foo = get('foo');
```

Combined, this solution satisfies all of our goals:

  - Easy to use
    Single API to read configs.
  - Centralised
    Single `values.js` where all config is set.
  - Secure
    Only the values you declare as being safe for the client get sent to the client.
  - Allows for build and execution time configuration
    Values are interpreted in a combination of build and runtime, with the client config being generated and sent with each HTTP response. This allows us to provide both types of configuration values.

There is a trade off for this solution though: Flow type checking and auto-complete on reading your config values will no longer exists.

To ease this pain I have included a lot of checks within the helpers and configs which ensure that you aren't trying to read a value that does not exist.

---

I hope this explains some of the reasoning and history on how we ended up with the currently proposed solution that is in the `next` branch.

I am open to suggestions, especially around the type safety of the `get` helper.  One solution to this is to create specific "get" instances for each type.

For example `getString`, `getBool`, `getObject`.  At least we could put some runtime checking within, and throw out error messages if the unexepected type was returned.  The current `get` helper only checks that the config value exists, not the expected type.  It throws if the config value path does not exists, providing a helpful message.

Thoughts?

**Comment by amcsi** [comment]
Ah okay, so the `get()` function is necessary to be able to conditionally get the values in different way depending on whether it's the server or the client reading it.
But couldn't you just decide on a global variable name in which to store the config values and just when requesting for the config values, conditionally return the global object in case of the client, otherwise return an object from values.js in case of the server? Apologies once again if there's something I missed, I'm not that experienced as a frontend dev.

Cool that you are putting so much effort into trying to make the project really usable.

**Comment by ctrlplusb** [comment]
Don't worry, I appreciate the feedback, and it sounds like you know what is going on! :) 

Its really important for me that these concepts are easy to grasp for people new to the project.  If you can't easily understand the decisions that I have made then it makes it that much harder to evolve the project into something that meets your own requirements.  So please never feel anxious about calling me out on a part of the project that is needlessly complex.

This is an interesting point you are making.  It would remove the extra layer of abstraction.  Let me have a play with this concept.  I am sure I can still make it secure.  I'll get back to you. :)

**Comment by amcsi** [comment]
What is confusing is knowing what you can and can't do in the server/client/whatever context and comprehending the steps of what gets compiled to what, or what is just lazily evaluated from what and stuff like that.

**Comment by ctrlplusb** [comment]
@amcsi it was an interesting idea returning one of two objects depending on client/server. As it could mean that we get the flow auto-complete.

I tried out a few things, but getting the flow typing to work correctly is exceedingly difficult.  As flow needs to be able to infer the structure of the server values object and the client values object.  We could create types to represent them, but that adds another layer of manual synchronisation as you would need to update the types every time you updated the value objects, and even then flow may complain that the types don't match what you are giving it.

So then I thought the easiest may be to get the client values object to match the structure of the server values object, but override it's properties making use of getters (like @enten did above) which would throw errors on properties that cannot be accessed by a client (also, the actual values wouldn't have been included in the getter implementation).   I thought if we had a matching object structure then flow would nicely handle the usage of the objects for us in code.  Unfortunately this seems a bit too clever for the flow inference engine.

We have to check access of each config property and throw if it is invalid so I think it is much simpler to stick with my `get` abstraction.

If anyone else has some insight here or is a flow master then I would appreciate your thoughts. :)

**Comment by amcsi** [comment]
Ok, I see how Flow may not work either way.

It might still be worth considering the two objects method anyway just for simplicity. The config defaults should probably be defined globally in the config source anyway rather than an accessing by accessing basis like your earlier code examples implied e.e. `get('configKey', 'defaultValue')`

**Comment by ctrlplusb** [comment]
Aaah, I see there might be more confusion here.  The get API doesn't provide defaults - those are paths.

So give the following config: 

```js
  {
    foo: {
      bar: {
        baz: 1
      }
    }
  }
```

You would access `baz` like so:

```js
import { get } from './config';
console.log(get('foo', 'bar', 'baz'));
```

This lets the `get` API track down the config object and ensure that each part you are requesting exists.  It can then throw a helpful error.

```js
get('foo', 'baz'); // throws Error('Requested config "foo.baz" does not exist')
```

We could provide an alternative approach here if it is more obvious.

```js
get('foo.bar.baz')
```

Slightly more overhead on the split, but memoization could be introduced if needed, amongst other techniques.

**Comment by amcsi** [comment]
Oh I see now.
Sure, sounds good then.
One thing: dynamic arguments might now be a good idea for the simple reason that you are locking yourself down from ever being able to add another argument to the method in the future.
Maybe `get(['foo', 'bar', 'baz'])` might be a good idea like `getIn()` in https://facebook.github.io/immutable-js/#nested-structures, or just `get('foo.bar.baz')`

**Comment by ctrlplusb** [comment]
Very good point, I shall certainly use that!  Thanks! :)

**Comment by ctrlplusb** [comment]
@amcsi I've done yet another simplification parse.

The config is 95% consumed by the `./src/server` and `./src/tools` folders.  Both of these cases are considered "safe" as they get executed in our private environments build/server.  So I have decided we must just expose a single configuration object at the `./config` root path.

Within that folder you there is also a `clientConfigFilter.js` which allows you to specify the configuration values that should be considered safe/needed to be exposed to the client bundle.

``` 
  |- config
      |- index.js // Contains the configuration values
      |- clientConfigFilter.js // A set of filters defining the config values that 
                               // can be exposed to the client.
```

So now you can use the config object "as normal" in the server/tools directories.

Example:

```js
import config from '../config';

app.listen(config.port, () => console.log('Started'));
```

We get flow help and all of that. Yay!

---

Oki, so now for the other src folders.  Namely `./src/client` and `./src/shared`.  All the code in these folders are expected to be bundled and sent to user's browsers.  Therefore if accessing configuration in these cases you must use the configuration helpers that are now located at `./src/shared/utils/config`.  This helper will ensure that the correct configuration object is resolved (i.e. the window object for a browser instance) and return the config value.

Example:

```
import { safeConfigGet } from '../shared/utils/config';

export default function Home() {
  return <h1>{safeConfigGet('message')}</h1>;
}
```

The documentation will need to be updated to explain why it is like this.  Also, if you accidentally import the `./config` into the `./src/client` or `./src/shared` folders then the build process will throw an error with a helpful message telling you to instead use the `safeConfigGet` helper within these source folders.  So you wouldn't even need to be thinking about it.  The system will guide you in the right direction.

Do you think this is a bit better?

**Comment by ctrlplusb** [comment]
@enten would appreciate your eyes on this too.

I'm working on it now. :)

**Comment by ctrlplusb** [comment]
Ok, I've pushed another update to `next`.  I am pretty happy with this solution now.  We have mostly the same API as before I started this update, and have rather introduced a new API for accessing configs within a `shared` or `client` module.

I need to update the README to reflect the latest.

**Comment by amcsi** [comment]
Sounds really good!
Please make sure to explain it in the docs too

**Comment by ctrlplusb** [comment]
Nice. Yep, just did a final cleanup round.  Looking much better.

I'm finishing off the docs and then will push this. :)

**Comment by ctrlplusb** [comment]
Done. :)

@amcsi - Do you mind reviewing the `/config/README.md` as well as comments/code within the configuration implementation?

**Comment by ctrlplusb** [comment]
Staged on `next`...

**Comment by amcsi** [comment]
I'm at work at the moment, you're going to need to give me some time

**Comment by ctrlplusb** [comment]
No problem.  I am leaving this on the `next` branch for a bit.  I want to get a few people to try it out if possible.

Thanks

**Comment by amcsi** [comment]
I got to read it now.
That's really amazing documentation you wrote, I'm really impressed!

**Comment by amcsi** [comment]
@ctrlplusb Alright I'm already using the v11 redux branch, and yes, finally this config stuff is really great and simple to work with! And finally I'm able to have different configuration on run time rather than build time
