### ISSUE TITLE
Proposal - Swap regenerator-runtime, transform-runtime, and polyfill.io

### ISSUE THREAD

**Issue by strues** [ctrlplusb/react-universally#265]
It's possible using `fast-async`. https://github.com/MatAtBread/fast-async

Most work I do outside of here, I never use regenerator-runtime, transform-runtime or polyfill.io / babel-polyfill

**Comment by ctrlplusb** [comment]
Interesting @strues thanks for this.  I will look into it. :)

**Comment by ctrlplusb** [comment]
Hmmm, so I am not sure we can drop polyfill.io (or alternative babel-polyfill) because we don't know what ES features people may end up using - we expose Sets and all sorts via the babel-latest preset.  I am surprised you haven't hit issues with older IE browsers if you aren't using any polyfill services.  What browsers do you target?

We could replace `regenerator-runtime` with `fast-async` but would this then mean that generator syntax would fail in browsers?  We expose generators as a feature as it's an ES2015 feature right?

Maybe we could add it as a comment above the current `regenerator-runtime` import?  Saying something like "if you 100% know you won't use generators and are instead interested in just the async/await syntax then consider using this...".

**Comment by ctrlplusb** [comment]
Here is a babel repl session using the same presets/plugins as us.  Babel doesn't appear to transpile everything.  It wants to rely on polyfills for some of the functionality.

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-3&experimental=false&loose=false&spec=false&code=const%20foo%20%3D%20new%20Set()%3B%0Afoo.add(1)%3B%0Afoo.add(2)%3B

**Comment by ctrlplusb** [comment]
I'll close this for now @strues but let me know if there is another option. :)
