### ISSUE TITLE
Feature branch work for v12 release

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#294]
___Note: I will push all the completed items below when I merge `next` into `master`___

Remove:
 - [x] jest (it is now in the main branch)

Add: 
 - [x] flow

Sync with v12:
 - [x] apollo
 - [x] found
 - [x] glamor
 - [x] koa2
 - [x] mobx
 - [x] postcss-sass
 - [x] styled-components
 - [x] styletron

Other: 
 - [x] redux - rename this branch to redux-opinionated as it relies on `flow`.

**Comment by ctrlplusb** [comment]
Releasing in the morning. :)

**Comment by lucianlature** [comment]
Little update from my side, guys. Sorry for the delay, parenting two very active young girls keeps me occupied 24/7. 

So, I have a working example of `preact` instead of React, however, on `SSR`, the rendering is still performed by `React`. For some reasons, `preact-render-to-string` does not work as expected for our example, it will return back `[Object object]` instead of the html markup.

Since we're talking about `preact`, I also have started on `feature/inferno` branch, this one aims to replace `React` with [Inferno](https://github.com/infernojs/inferno).

I would like these two features to be added for the `v12` release.

**Comment by ctrlplusb** [comment]
No worries at at @lucianlature - I have a little one myself, and feint at the idea of having two of them around! Haha

Interesting issue with `preact`.  Perhaps throw out a PR and we could join heads to see what is up with the SSR case.

Thanks for your continued interest and contributions. :)

**Comment by ctrlplusb** [comment]
Sorry for the delay everyone.  I felt uncomfortable releasing this until I came up with some decent solutions for the redux branch.  Track the final piece of the puzzle here: #302
