### ISSUE TITLE
[v13] Browser Back/Forward button in development mode logs "Warning: forceUpdate..."

### ISSUE THREAD

**Issue by haddoq** [ctrlplusb/react-universally#350]
If I use the browser back and forward button in the next branch I get this message in the console:

> Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the History component.

If i remove the react-async-component code the warning dissapears.

**Comment by ctrlplusb** [comment]
Thanks for the report @haddoq!

**Comment by birkir** [comment]
I found this bug as well few days back.

What I did was to disable the state output of the code split component.

```diff
@@ server/middleware/reactApplication/ServerHTML.js @@
    onlyIf(
-     asyncComponents,
+     process.env.BUILD_FLAG_IS_DEV === false && asyncComponents,
      () => inlineScript(
        `window.${asyncComponents.STATE_IDENTIFIER}=${serialize(asyncComponents.state)};`,
      ),
    ),
```

Few notes:

1) The development server will not rehydrate state of code-splitted components.
2) This may or may not cause problems for you.
3) It's okay for me as I'm using mobx to handle state. (I don't use React's default state engine / setState).
4) To fix this, something big needs to happen in the underlying package `react-tree-walker`.

**Comment by ctrlplusb** [comment]
@birkir this is amazingly insightful thank you!  I have some ideas forming...

**Comment by ctrlplusb** [comment]
Hey all; I did some digging and because an initial parse is done on the react application (using `react-tree-walker`) some listeners get attached based on the `Route` components.  The `Route` component in React Router does have a `componentWillUnmount` lifecycle event that cleans up these listeners, but it is against the SSR APIs / behaviour to fire this event. Therefore the listeners aren't cleaned up and then try to respond to events from our actual application execution.  As this logic is lifted from the Apollo Stack, anyone using Apollo Stack with the latest React Router will experience this same issue.

I have logged an issue on React Router.  Let's see if they guys have any sage advice for us.

https://github.com/ReactTraining/react-router/issues/4566

**Comment by ctrlplusb** [comment]
Hey all. I have been trying to create a minimal example for the issue report on react router but it's a tricky case to recreate.

I have since discovered that this issue only arises in development mode. A production build/start works fine.  So there appears to be something about the development build that leads to this error occurring.  The error itself seems innocuous - the only effect it has is outputting to the console.

I am going to keep this as a "known issue" for now and will add it to the FAQ.  In the interim I suggest you just ignore the console warnings rather than disabling the state in development as suggested by @birkir above - this would break the checksums in SSR mode.  I find it's better to have the development environment as closely represent the behaviour of your production environment too (bar the hot reloading).

Again, this warning only occurs when using the browsers back/forward buttons when in development mode, but it has no effect on the app other than printing a warning message to the console.

**Comment by birkir** [comment]
Ok good to know.

Are you sure the warnings are not happening in production as React won't output any warnings messages into the console while not using the development build.

In my case, these messages are really annoying and I would suppress them if I could identify them  from other forceUpdate warnings caused by other things.

Maybe I'm just picky wanting a clean console 😄 

I'll investigate this further when the time comes! Thanks for the input.

**Comment by ctrlplusb** [comment]
Hmmm, that is a very good point! I initially took it as an "error" being thrown by the code in question, not that React was handling an expected error case.  Definitely needs some more debugging then.  The message itself states that it will be a noop, I guess my only concern is where and how loose component instances are staying alive.  Thanks for the insight!

**Comment by ctrlplusb** [comment]
New release of react-router will sort this. 🎉

**Comment by ctrlplusb** [comment]
Sorted by #381 

Thanks @datoml!

**Comment by birkir** [comment]
@ctrlplusb Investigating another bug, so asking if you know what change in react-router solved this issue?

**Comment by ctrlplusb** [comment]
No worries. It was their pub/sub system they used to track route changes.  There are some lengthy blog posts around about the move away from this.
