### ISSUE TITLE
Upgrade to latest react-router (v4 beta)

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#356]
@ryanflorence ["promises"](https://twitter.com/ryanflorence/status/826116201730318337) us that the API in the beta can be considered stable.

SSR checksum is currently broken though. Awaiting https://github.com/ReactTraining/react-router/pull/4484

**Comment by strues** [comment]
Let's hope so! I've been delaying upgrading to RR4 anywhere as there's been **so many** changes. Yet to find a data loading technique that feels "right" with the new changes.

**Comment by carsonperrotti** [comment]
I've been working around that bug all weekend. It's so frustrating that they moved the library into a subdirectory so you can't even target the branch to get the latest.

**Comment by ctrlplusb** [comment]
@carsonperrotti sorry to hear. It does sound like it will land soon though. 🤞

**Comment by diondirza** [comment]
I suppose to mitigate this error you should install earlier beta.
Add this line into `package.json` will solve the issue for this time
```
"react-router": "4.0.0-beta.4",
"react-router-dom": "4.0.0-beta.4",
```

**Comment by diondirza** [comment]
@ctrlplusb I have updated my [PR](https://github.com/ctrlplusb/react-universally/pull/351) to solve this issue.

**Comment by carsonperrotti** [comment]
@diondirza When I tested earlier versions, I thought the issue still existed in beta 4. Did you not find that to be the case?

**Comment by diondirza** [comment]
@carsonperroti nope, I have used beta 4 before and error exist in beta 5. Since new react router using new `react-router-dom` package name it has dependence with original package `react-router` if you look at their package.json it has ^ mark. So when you request beta 4 `react-router-dom` it will accept latest beta `react-router` as dependence. Therefore error will also exist if you just request exact version of `react-router-dom` beta 4 instead by telling explicitly what version of `react-router` the error will gone for good. You could try to fresh clone my fork with `update-router-beta` [branch] (https://github.com/diondirza/react-universally/tree/update-router-beta) to prove it. Or you could do it in your local, but don't forget to delete node_modules folder and refetch again.

**Comment by diondirza** [comment]
@ctrlplusb @carsonperrotti looks like react-router already release beta-6, looks promising right now. I'm still reviewing though, hopefully won't find another bug in it. My [PR](https://github.com/ctrlplusb/react-universally/pull/351) also updated as well.

**Comment by ctrlplusb** [comment]
I have this running on v13. Thank you so much @diondirza for your helpful PR! I will credit you with this. :)

We just need to figure out how to return a 404 status code when no Route is matched.

**Comment by diondirza** [comment]
@ctrlplusb you are welcome, ah I missed that part I thought it wasn't necessary. Anyway I found how to solve that problem and I have send you a [PR](https://github.com/ctrlplusb/react-universally/pull/357) for it.

**Comment by ctrlplusb** [comment]
Done!

Thanks goes to @diondirza for completing this for us. 🙏
