### ISSUE TITLE
Fix polyfill io configuration - currently breaks older browsers 😢

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#374]
I misconfigured the polyfill.io service.  I meant to add `Symbol` as a feature, instead I made it the _only_ feature being polyfilled!  Woops 🙈

It should be:

```
https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Symbol
```

You can find this in the project configuration file.

**Comment by birkir** [comment]
Fixed in next with f802485

**Comment by diondirza** [comment]
Guys, I have tried this setting on production level seems it breaks on android browser. I have to change it back to non parameter version and my app working normal now.

```html
https://cdn.polyfill.io/v2/polyfill.min.js
```

I think it doesn't add all Symbol feature, because in android browser the error told me that `Symbol.Iterator is not a function` even I have changed it to

```html
https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Symbol,Symbol.iterator
```

**Comment by ctrlplusb** [comment]
Hey @diondirza 

Thanks for this.  More fuel towards #393

**Comment by birkir** [comment]
We did a mistake, I was digging into our previous starter-kit because I remembered having similar problems there in the past.

I found `features=default,es6`. Damn! This fixed all our issues.

**Comment by ctrlplusb** [comment]
On next
