### ISSUE TITLE
Acessing request variables such as navigator in SSR

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#385]
Sometimes, elements from the navigator, such as the user-agent are necessary in order to ensure that client side and server side rendering are identical. 

An example is: https://github.com/callemall/material-ui/issues/4466

So, what is the best way to add this kind of variable? Perhaps it should be added by default in react universally.

**Comment by birkir** [comment]
We probably wont add this unless we have a module that depends on it. We are not trying to cover every use-case with react-universally, it's easily extensible so we leave it up to the users.

You can certainly provide serialized navigator object in `ServerHTML.js` that can be read by other components. Also if you have a redux state you can use that.

But please post questions to Stack Overflow.

**Comment by mschipperheyn** [comment]
I didn't find a react-universally SO tag

**Comment by birkir** [comment]
Well, it doesn't have to be tagged with the name of a project, rather high level terms of what the problem is about, like for example http://stackoverflow.com/questions/35481084/react-starter-kit-and-material-ui-useragent-should-be-supplied-in-the-muitheme is tagged with `react` and `isomorphic-javascript` which seem to be descriptive enough.

**Comment by smirea** [comment]
@mschipperheyn I use materialUI in a project i'm working on with this starter. you can setup the MUI provider with a theme and pass it the userAgent - since it's the only navigator property it needs. The thread you referenced has an example:

https://github.com/callemall/material-ui/issues/4466#issuecomment-226173393

I just plucked it from the request and added it to the app in `server/middleware/reactApplication` (for v12 of the starter):

```jsx
  const app = (
    <CodeSplitProvider context={codeSplitContext}>
      <ServerRouter location={request.url} context={reactRouterContext}>
        <MuiThemeProvider muiTheme={generateMuiTheme(request.headers['user-agent'])}>
 ...
```

**Comment by mschipperheyn** [comment]
Thanks @smirea , I applied this for V13, but subsequently ran into https://github.com/callemall/material-ui/issues/4466#issuecomment-239168446

What I did:

server/middleware/reactApplication/index.js

	export default function reactApplicationMiddleware(request, response) {
	[...]
	const app = (
		<StaticRouter location={request.url} context={reactRouterContext}>
			<App
				userAgent={request.headers['user-agent'] || 'all'}
			/>
		</StaticRouter>
	);


shared/App.js

	function App({ userAgent }) {

		return (
		  <Provider store={ store }>
			  <IntlProvider defaultLocale="pt">
				  <MuiThemeProvider
					  muiTheme={getMuiTheme({
						  userAgent: userAgent || (navigator && navigator.userAgent),
					  })}>
					  <Switch>
						  <Route exact path="/" component={Home} />
						  <Route component={Error404} />
					  </Switch>
				  </MuiThemeProvider>
			  </IntlProvider>
		  </Provider>
		)
	}

	export default App;

Moving forward I guess.
