### ISSUE TITLE
[v13] Error when disableSSR: true 

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#386]
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
        at ServerHTML (../build/server/webpack:/server/middleware/reactApplication/ServerHTML.js:77:8)

it happens because of 

     ...onlyIf(helmet, () => helmet.meta.toComponent()),

**Comment by birkir** [comment]
Duplicate of #362 

Thank you for the bug report but please search the issues before you post one, also please post questions to Stack Overflow as I have see you have been posting them as well.

**Comment by ctrlplusb** [comment]
@mschipperheyn, just to follow up on what @birkir is saying... 

We are super appreciative of your interest in this project and don't want you to feel like we are pushing you away into Stack Overflow 😀. However we are a very small team many of us with families and other commitments so using the issues list as a platform for general questions on technologies/implementation is probably not the best place as it increases our management overhead and we can't guarantee that you would be answered in a respectable amount of time.  I would like us to try and keep the issues list for the following:
 - bug reports 
 - feature requests
 - raising concerns/recommendations about current implementation
 - raising concerns/recommendations about documentation/comments

The above being said, I can appreciate we don't communicate this to everyone anywhere. I think considering this project has started to get an expansive audience it is probably up to us to create a template for issues so that everyone is informed up front on the above.

Also, if you aren't sure if a question belongs in Stack Overflow or here then please don't be afraid to post it here.  I certainly don't want to create a "fear to ask for help" culture, I only ask that we all be mindful that this is an open source project being run by time donated from us all so any and all help is appreciated.  😀

**Comment by mschipperheyn** [comment]
yeah, ok sorry. I'd be happy to ask on SO, I just couldn't find a react-universally tag there, so when I *think*  it might be platform specific, I ask it here.

**Comment by ctrlplusb** [comment]
Yep, no problem with that, understand blue it can be difficult to determine if it's platform vs 3rd party.
