### ISSUE TITLE
Feature branch cull

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#387]
Hey all;

I am thinking of doing a "feature branch" cull to reduce management overhead.  I think we have far too many styling options, and should probably keep this down to just a couple at most - one to represent CSS in JS and another to represent CSS/SASS style.

Thoughts?

I would appreciate any arguments on which of the other branches we should keep/remove.  I'd rather us have fewer, higher quality implementations. 

---- 

___UPDATE___

Appreciate the input everyone!

My own opinion (having also considered yours below).

Keep the following, with the following chores required against each of them.
  - redux 
    - [ ] update to next
    - [ ] simplify, making it un-opinionated, i.e. no react-jobs etc.
  - mobx
    - [ ] update to next
    - [ ] ensure it is bare bones / un-opinionated
  - styled-components
    - [ ] update to next
    - [ ] update to v2 of styled-components
    - [ ] implement some styled-components best practices around examples
  - postcss-sass (we have a lot of issues containing questions about sass, so def a keeper)
    - [ ] update to next

The rest I will put up for offer for anyone to host as a standalone repo (e.g. `react-universally-apollo`), with preference going to the original creator of the branch, and then to any volunteers. Any branches that fail to pick up a volunteer will be deleted.  Lets give a 2 week time period for this to happen.  i.e. kill date 27/03/2017

If any of you wish to take over the branch as described please let me know and I will edit the list below:

  - [ ] apollo
  - [ ] koa2
  - [ ] flow
  - [ ] found
  - [ ] glamor
  - [ ] preact
  - [ ] styletron

**Comment by birkir** [comment]
I'm with you on this one, feature branches seem to get left behind.

**Some notes:**
 - feature/jest is already merged with master, right?
 - I would go with feature/postcss-sass rather than feature/styled-components, feature/styletron and feature/glamour.
 - the feature/found router doesn't seem to be very popular on npm.
 - redux and mobx sis a must IMO.

One option is to add a step-by-step guide to add a certain feature in the docs or wiki. Or simply show the diff, then we don't have the overhead of keeping it in sync with master or next, etc.

If they are kept in the ./internal/docs, they could live within `master` or `next` (or in other words: they are in sync to their relative branch all the time).

**Comment by LorbusChris** [comment]
@ctrlplusb Yup, also agreeing to this.

I like the idea of retaining one SASS and at least one CSS in JS branch for the purpose of comparing the two.

I'm also curious how Styled-Components v2 will turn out. I'm likely gonna use it in conjunction with https://github.com/styled-components/polished

Regarding the Found branch: Lately I haven't had any time to put into maintaining it. I however plan to pick that up again at some point (won't be before mid-April though). If you plan on eliminating that branch, please give me a heads up - I'll happily maintain it in my own branch :)

@birkir for me the Found router is especially interesting because it allows for easy Relay-integration, which I what I eventually plan to do.
 
Therefore, the branches that I'd ideally like to be kept are:
- styled-components
- found
- redux

**Comment by oyeanuj** [comment]
+1 on keeping `styled-components` and another `postcss-sass` one. similar to @birkir's suggestion, I think keeping a guide or a link to a previously existing branch for similar topics would be quite helpful. For example, `styled-components` and `glamor`, `react-router 2/3` and `found`. I imagine the changes aren't drastic enough that can't be covered in a guide or a recipe.

**Comment by strues** [comment]
+1 breath of fresh air. The amount of branches is overwhelming. I'd argue that Redux should be the default branch to eliminate another additional branch. No statistical evidence so this might be off base, but I'd imagine most people interested in universal rendering apps are going to be adding Redux/Mobx/Apollo anyways.

It's easier for the end user to strip away Redux if they wish to not use it.

**Comment by datoml** [comment]
Hmm...
How about removing all the branches and provide a documentation about how to implement a certain feature.
Ok, its a little bit more boilerplate for the user but at least they know how and why some parts have to be implemented that way.

Just an idea :)

**Comment by ctrlplusb** [comment]
Hey all, I have updated my original post.

**Comment by oyeanuj** [comment]
@ctrlplusb That sounds good. The only thing if I may suggest, is to keep links to the older versions fo the discontinued branches (or even just say Deprecated in big bold letters instead of deleting them). This way, if someone wants to integrate with those libraries, they have an example to look at.

In the absence of that, having guides/recipes would be super helpful but that might be more work to create (but again, they can just be links to the main files edited in the deprecated branch).

**Comment by fivethreeo** [comment]
This thread seems eerily silent :) I love the easy build provided by this repo. The async code splitting stuff confounds me. However redux I got pat down. I used the redux-opinionated branch to get going, I wanted to rebase my code against next but it seems this rebasing goes over a big merge. Would be great if this branch would be rebased by someone familiar with those changes and become master as I have seen suggested.Also the branch should switch to connectedrouter.

**Comment by ctrlplusb** [comment]
Hi all;

I am going to remove _all_ feature branches, they will be available within an archive repository:
https://github.com/ctrlplusb/react-universally-archive

Sorry, just think with the length of period that has gone by it would be more manageable to do this and then be able to add a couple back if needed.

Hope this doesn't upset anyone 😇
