### ISSUE TITLE
SSR rendering twice in `next` branch

### ISSUE THREAD

**Issue by kennethtruong** [ctrlplusb/react-universally#391]
Not sure if this is an issue but I noticed that when I console.log in `render` in Home or About for the branch `next` its getting called twice. If this is the expected behavior can someone explain to me why this happens? Thanks!

I tested the master branch and it seemed to be fine.

**Comment by strues** [comment]
Hey @kennethtruong the reason you're seeing a double console.log has to do with asynchronously loading the component.

Allow me to explain. Replace one of those logs with a `console.trace('hi')`.

**Doesn't render**
```
hi
Home @ Home.js:7
reactTreeWalker @ index.js:84
reactTreeWalker @ index.js:89
doWalk @ withAsyncComponents.js:104
(anonymous) @ withAsyncComponents.js:111
```

**Renders**
```
hi
Home	@	Home.js:7
....excluded for brevity
mountComponentIntoNode	@	ReactMount.js:104
perform	@	Transaction.js:140
batchedMountComponentIntoNode	@	ReactMount.js:126
perform	@	Transaction.js:140
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	ReactUpdates.js:97
_renderNewRootComponent	@	ReactMount.js:320
_renderSubtreeIntoContainer	@	ReactMount.js:401
**render	@	ReactMount.js:422**
(anonymous)	@	index.js:36
```

Notice in the second trace there's a render and in the first there isn't? The first time, essentially, the component is being explored in order to find out info before rendering.

The second trace illustrates the actual rendering of the component into the DOM.

@ctrlplusb Might be able to explain a bit better. It's late and Ive gotta hit the pillow. Hopefully that helps.

**Comment by kennethtruong** [comment]
Ohh I see! I had a tiny suspicion that it could have been related to the asyncComponent since that was one of the things that changed from master to next. Thanks for taking the time to my question!
