### ISSUE TITLE
[feature/mobx@next] forceUpdate(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by diondirza** [ctrlplusb/react-universally#399]
@birkir I also used mobx in my project, yet I cannot solved this issue for days. Since upgrading into next version I face this problem in client. Seems its triggered by calling code in my mobx store inside React's `componentWillMount() or componentDidMount()`. I have used your code sample in your repo **ueno-llc/starter-kit-universally** 

```
if (!this.context.ASYNC_WALKER_BOUNDARY) {
 // call mobx store function e.g fetch data or change value
}
```
But its only cover for async components with componentWillMount, how about if I want to call mobx store in componentDidMount scope? and what about my sync component? Seems it's not proper way to make all my component async.

I have made a sample in this [branch](https://github.com/diondirza/react-universally/tree/next-mobx-problem) 
Thoughts?

**Comment by birkir** [comment]
Hey @diondirza, the`this.context.ASYNC_WALKER_BOUNDARY` is a hack I used to make sure something would only fire once inside the componentWillMount, because **react-async-component** actually fires componentWillMount twice! (believe it or not).

But then again, the **react-async-component** is also responsible for the forceUpdate issue you are experiencing.

We had a recent problem with react router making the exact same behaviour, but I knew react-mobx also triggered it, but didn't want to follow it through.

I actually still use the solution I posted here: https://github.com/ctrlplusb/react-universally/issues/350#issuecomment-281135421, as I don't use the state, it's useless either way.

**Comment by diondirza** [comment]
I see. Well, i think  it's better to stick with **code-split-component** & **react-router-dom@4.0.0-beta.6** for now, seems quite stable for me. 

Upgrade it to **react-router-dom@4.0.0** and it didn't works well with **code-split-component** then change it to **react-async-component** will produce this errors. 

Kinda feel bad about it.

**Comment by diondirza** [comment]
Just realize this only happen in development server, as you said @birkir using your solution in that post sort this issue out. Yet now it print some react id in console, pretty weird.

**Comment by ctrlplusb** [comment]
Fixed with latest merge from `next` 🎉
