### ISSUE TITLE
CSS filename hash/fingerprint doesn't change on CSS only patch

### ISSUE THREAD

**Issue by bradbarrow** [ctrlplusb/react-universally#436]
### Context

Node v7.4.0
React Universally 12 and 13

### The issue

Changing only a CSS file before running `yarn build` results in no change to the CSS output.
The sha in the asset filename doesn't change, nor do the file contents.

This is unexpected, since the CSS should be extracted and sha'd separately. No classnames were changed, only rules so this should be a valid change.

### Steps to reproduce

1. Clone the repo
2. Run `yarn build`
3. `ls build/client/*.css and note the sha e.g. `index-aa82d9f216c877685074.css`
4. Add `.foo { color: red; } to the end of `shared/components/DemoApp/globals.css` and save
5. Run `yarn build`
6. `ls build/client/*.css and note the sha e.g. `index-aa82d9f216c877685074.css`

### Other notes

Changing a JavaScript file, even simply adding a comment, results in the CSS being correct.

**Comment by diondirza** [comment]
The problem that occurs to me only same hashing for every changes yet the content still get updated.

Easy fix for this is to let extract-text-plugin hashing the file. Extract text plugin configuration currently lean on hash of js entry chunk instead of hash of the file itself.

You can change this [line](https://github.com/ctrlplusb/react-universally/blob/master/internal/webpack/configFactory.js#L318) to
```
filename: '[name]-[contenthash].css', // lean on extract-text content hash, I preferred this
// or
filename: '[name]-[hash].css', // lean on webpack file hash
```

**Comment by bradbarrow** [comment]
@diondirza you're right, sorry the same content issue was just caching. That's my bad...got myself confused trying to debug this.

Your fix makes sense - thanks :)
