### ISSUE TITLE
Discussion: using Fusebox instead of Webpack

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#466]
[Fusebox](http://fuse-box.org/) ([repo](https://github.com/fuse-box/fuse-box)) is _a blazing fast js bundler/loader with a comprehensive API_.

In my opinion: it can be a great alternative to Webpack.

But I have no usage experience with it. May its API be more suitable to write an universal toolchain? We need to bench it.

**Does anyone have an usage experience with Fusebox?**

**Comment by mfrohberg** [comment]
I have been working with FuseBox for the last few months on a pretty decent sized universal React/Redux application. I think it is an incredible tool. I found myself trying to incorporate many of the concepts from this project. Ultimately I decided today to go back with webpack because of its ubiquity and the fact that fuse-box shines best with typescript.
