### ISSUE TITLE
yarn vs npm

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#470]
I kinda feel that npm is the "standard" and wonder if we should default a project like this to it.  npm@5 brings much of the same benefits, and in most cases would be one less dep to install.

**Comment by strues** [comment]
Biased toward yarn because it works all the time for me 🥇. When npm5 released I often ran into issues where packages wouldn't correctly install if say you first install w/ yarn and then used npm. 

Cool story, right? Yarn or npm whatever works for people. If we only use npm and not yarn, I'll attempt to break my `yr command`  habits

**Comment by ctrlplusb** [comment]
Hey all, we currently have a mix of npm and yarn running within the app (both lock files exist).  I'm gonna move to npm - it's pretty stable now since 5.3.0.  Yarn has the definite one up on npm if using monorepos but otherwise I don't think it brings that much more to the table that I wanna move away from what is essentially "standard".  Easier for people to initially onboard, and easy enough for those wanting to use yarn to simply switch over.
