### ISSUE TITLE
Running on plesk

### ISSUE THREAD

**Issue by Maiko1100** [ctrlplusb/react-universally#476]
Hi guys,

I have a question on how to run this project on a plesk server. Does anybody have any experience with this, because i feel like i'm doing it the wrong way.

Kind regards,

Maiko

**Comment by unleashit** [comment]
I'm pretty sure your issue is going to come down to weather you're able to install node.js on your server. Are you on shared hosting, or are you in control of the server? Usually if you have Plesk or CPanel... unless you installed them yourself... it means that you're on shared hosting with a LAMP (PHP) stack. You can't run React Universally without Node. You're better off getting a VPS on something like Digital Ocean and learning how to use the command line.
