### ISSUE TITLE
Promise undefined for offline build

### ISSUE THREAD

**Issue by alexanderfrey** [ctrlplusb/react-universally#490]
Hi there !

First of all thanks for your amazing work. I just ran into a problem with the client offline build (yarn build) that is running fine for most modern browsers but not so for IE 11. 
It seems that polyfilling is not being run early enough (or run at all) for the offline.html compilation.

S2R:

- Check out master branch

- run yarn build

- start local webserver in ./build and open offline.html with IE11. 

Does anyone experience similar behavior ? 

Any help is very much appreciated.

Best,
Alexander

**Comment by unleashit** [comment]
Haven't done much testing of service workers on my project because I think it'll take significant work to really support. But when I turn them on they're pretty much working as expected  (i.e. fine on static pages included in the main bundle, but problems on code split components or with API calls).

IE11 doesn't support Service Workers and I don't think polyfill.io covers it. I just tested in my setup, and while I don't have the issues you have with promises (as long as polyfill is on), I simply get a white page with "Can't reach this page" if I try to reload while the server is down/off.

**Comment by ctrlplusb** [comment]
Gonna do some heavy IE testing based on other issues. Will close this for now.
