### ISSUE TITLE
Question: why use both dotenv and webpack 2 --env?

### ISSUE THREAD

**Issue by cloud-walker** [ctrlplusb/react-universally#89]
Why not just:
```json
{
  "development": "node ./tools/development/server",
  "build": "npm run clean && webpack --config ./tools/webpack/client.config.js && webpack --config ./tools/webpack/server.config.js",
  "prestart": "npm run build",
  "start": "node build/server/main.js"
}
```
and let the .env manage the **NODE_ENV** thing, like the other variables?

Its just a question trying to understand if there are any reason about that. Thanks!

**Comment by cloud-walker** [comment]
The prestart script is just an idea of the moment, just to ensure that npm start will have the build first

**Comment by ctrlplusb** [comment]
It's an interesting questiom, thanks!

I shall def give this some thought. 

Simplification is always appealing. :-)

**Comment by cloud-walker** [comment]
So, in my project, I can safely put NODE_ENV into the .env file right?

**Comment by ctrlplusb** [comment]
Yep, there is no reason for you not to. :-)

I haven't had time to go through this all yet, but I will let you know when I have.

**Comment by ctrlplusb** [comment]
Hi @cloud-walker 

Eventually looked at this.  My thinking for having the NODE_ENV be controlled via the webpack config rather than the .env file is that it gives us the capability to easily run the project in development or production mode per environment.  I like to be able to run both on my development environment for example.

I am going to close this for now.  If you did end up adding NODE_ENV to your .env file please let me know how your experience was and if you had to make another other changes to the workflow.

Thanks
